### PR TITLE
Remove hardcoded python environments

### PR DESCRIPTION
**Pull request by scristobal**
Try to avoid the hard-coded hash on `devcontainers.json` by setting poetry config

### CODE REVIEW

**Comment by scristobal** [comment]
@tonofll and @ManuelAngel99 could you please review and test this on your machines, it should load the python environment automatically w/o the hard-coded hash 🤞🏻

**Review by tonofll — DISMISSED** [review]
Tested and it's working. This is awesome, I didn't like at all the fact of hardcoding the hash. Nice 🚀

**Comment by tonofll** [comment]
Interesting reference here about what should be placed in `pyproject.toml`and `poetry.toml`https://github.com/python-poetry/poetry/issues/2937#issuecomment-770543652

**Comment by tonofll** [comment]
When testing this change, I'm struggling a bit while configuring black or ruff the second time I trigger de devcontainer:

1. Build python-example using Rebuild Container without Cache
2. It works as expected, now click Reopen locally
3. Trigger again Rebuild Container without Cache
4. VSCode extensions are not installed properly.

image

**Comment by scristobal** [comment]
> LGTM, tested both containers and works fine
> 
> I don't think it is an issue, but some dependencies are not fixed totally, some version change on `poetry.lock` when building the python dev container
> 
> Captura de pantalla 2023-04-12 a las 12 06 44
> 
> Captura de pantalla 2023-04-12 a las 12 10 34

good catch!!! This is because we are using `poetry update` instead of `poetry install` at https://github.com/databeacon/devcontainers-examples/blob/ee513dc218c6a19189cd37d1bbd0e9f0ae49ddb4/.devcontainer/python-module-devcontainer/devcontainer.json#L23

@tonofll we need to change this in all repos to use the lock files and avoid update dependencies each time the devcontainers are launched.

**Review by tonofll — APPROVED** [review]

**Pull request merged**
